from math import *

NUM_W_SAMPLE_AREAS = 4
NUM_H_SAMPLE_AREAS = 4
AREA_DIVISIONS = 5


SAMPLE_WIDTH = 600
GROSS_W_DIV= int(SAMPLE_WIDTH/NUM_W_SAMPLE_AREAS)
FINE_W_DIV = int(GROSS_W_DIV/AREA_DIVISIONS)

SAMPLE_HEIGHT = 600
GROSS_H_DIV = int(SAMPLE_HEIGHT/NUM_H_SAMPLE_AREAS)
FINE_H_DIV = int(GROSS_H_DIV/AREA_DIVISIONS)

POINT_R = 12

EM_OFFSET = 10

